apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  replicas: 3
  template:
    metadata:
      name: frontend-service
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: gcr.io/codeone2019/frontend-service
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: frontend-service
