apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: gcr.io/devoxx2019/frontend-service
    jibGradle: {}
    context: frontend-service
  - image: gcr.io/devoxx2019/vote-service
    jibGradle: {}
    context: vote-service
  - image: gcr.io/devoxx2019/notification-service
    context: notification-service
