apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
  labels:
    app: vote-service
spec:
  replicas: 1
  template:
    metadata:
      name: vote-service
      labels:
        app: vote-service
    spec:
      containers:
        - name: vote-service
          image: gcr.io/devoxx2019/vote-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
      restartPolicy: Always
  selector:
    matchLabels:
      app: vote-service
