apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: gcr.io/codeone2019/frontend-service
    jibGradle:
      {}
deploy:
  kubectl:
    manifests:
    - k8s/frontend-deploy.yaml
    - k8s/frontend-svc.yaml
